"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export const languages = ["en", "fr", "es", "ru", "it", "sr"] as const;
export type Language = (typeof languages)[number];
const labels: Record<Language, string> = { en: "English", fr: "Français", es: "Español", ru: "Русский", it: "Italiano", sr: "Srpski" };

const en = {
  start: "Start viewing", ready: "The gallery is ready", loading: "Preparing the gallery", intro: "Enter a quiet room of cut paper, found memory and imagined landscapes.", count: "An exhibition in nine works", help: "Help", guestbook: "Guestbook", hint: "Drag to look around. Click an artwork or the door to enter the next room.", order: "I want to buy this postcard", back: "Back to exhibition", close: "Close artwork", exhibition: "Online exhibition",
  language: "Language", returnExhibition: "Return to exhibition", hall2: "Hall 2", visitorsYourPage: "Visitors’ book · Your page", guestbookQuestion: "What did you like most?", guestbookIntro: "Leave a short note in the visitors’ book. No account or email is needed.", developmentSheets: "Development mode: connect Google Sheets to enable submissions.", displayName: "Display name", optional: "optional", yourNote: "Your note", favouriteArtwork: "Favourite artwork", noSelection: "No selection", noteSuccess: "Thank you. Your message has been added to the guestbook.", leavingNote: "Leaving your note…", leaveNote: "Leave this note", noteTooFast: "Please take a moment with your note before sending it.", noteCooldown: "Please wait a moment before leaving another note.", noteError: "Your note could not be sent.", noteLength: "Please leave a slightly longer note.", fromVisitors: "From the visitors’ book", notesHall2: "Notes from Hall 2", demonstration: "Demonstration entries", openingGuestbook: "Opening the guestbook…", guestbookError: "The guestbook could not be reached.", tryAgain: "Try again", emptyGuestbook: "The first page is waiting for a note.", showMore: "Show more", remembered: "Most remembered", anonymous: "Anonymous visitor",
  postcardRequest: "Postcard request", artwork: "Artwork", postcardIntro: "Leave your email — we will contact you when the postcard is available.", connectSheets: "Connect Google Sheets to enable submissions.", sending: "Sending…", leaveEmail: "Leave email", formTooFast: "Please take a moment before sending.", formCooldown: "Please wait a moment before submitting again.", formError: "We could not save your email. Please try again.", invalidEmail: "Enter a valid email address.", received: "Received", thankYou: "Thank you.", receivedText: "Your email and selected artwork have been saved. We will contact you when the postcard is available.", returnArtwork: "Return to the artwork", closeOrder: "Close postcard request", infoAbout: "Information about", loadingHall: "Loading exhibition hall", lightingControls: "Lighting controls", chooseArtwork: "Choose an artwork", openGuestbook: "Open guestbook", navigation: "Exhibition navigation", catalogueFallback: "Your browser cannot display the 3D halls. Catalogue view is open instead.", previousWork: "Previous work", nextWork: "Next work", skipContent: "Skip to content", morning: "Morning", day: "Day", evening: "Evening", night: "Night"
} as const;
type MessageKey = keyof typeof en;
type Dictionary = Record<MessageKey, string>;

const messages: Record<Language, Dictionary> = {
  en,
  fr: { ...en, start:"Commencer la visite",ready:"La galerie est prête",loading:"Préparation de la galerie",intro:"Entrez dans un espace silencieux de papier découpé, de souvenirs et de paysages imaginés.",count:"Une exposition en neuf œuvres",help:"Aide",guestbook:"Livre d’or",hint:"Faites glisser pour regarder autour de vous. Cliquez sur une œuvre ou sur la porte.",order:"Je veux acheter cette carte postale",back:"Retour à l’exposition",close:"Fermer l’œuvre",exhibition:"Exposition en ligne",language:"Langue",returnExhibition:"Retour à l’exposition",visitorsYourPage:"Livre d’or · Votre page",guestbookQuestion:"Qu’avez-vous préféré ?",guestbookIntro:"Laissez un petit mot dans le livre d’or. Aucun compte ni e-mail n’est nécessaire.",developmentSheets:"Mode développement : connectez Google Sheets pour activer les envois.",displayName:"Nom",optional:"facultatif",yourNote:"Votre message",favouriteArtwork:"Œuvre préférée",noSelection:"Aucune sélection",noteSuccess:"Merci. Votre message a été ajouté au livre d’or.",leavingNote:"Envoi du message…",leaveNote:"Laisser ce message",noteTooFast:"Prenez un instant avant d’envoyer votre message.",noteCooldown:"Veuillez patienter avant de laisser un autre message.",noteError:"Votre message n’a pas pu être envoyé.",noteLength:"Veuillez écrire un message un peu plus long.",fromVisitors:"Dans le livre d’or",notesHall2:"Messages de la salle 2",demonstration:"Messages de démonstration",openingGuestbook:"Ouverture du livre d’or…",guestbookError:"Le livre d’or est inaccessible.",tryAgain:"Réessayer",emptyGuestbook:"La première page attend un message.",showMore:"Afficher plus",remembered:"Œuvre marquante",anonymous:"Visiteur anonyme",postcardRequest:"Demande de carte postale",artwork:"Œuvre",postcardIntro:"Laissez votre e-mail — nous vous contacterons lorsque la carte sera disponible.",connectSheets:"Connectez Google Sheets pour activer les envois.",sending:"Envoi…",leaveEmail:"Laisser mon e-mail",formTooFast:"Prenez un instant avant d’envoyer.",formCooldown:"Veuillez patienter avant un nouvel envoi.",formError:"Impossible d’enregistrer votre e-mail. Réessayez.",invalidEmail:"Saisissez une adresse e-mail valide.",received:"Reçu",thankYou:"Merci.",receivedText:"Votre e-mail et l’œuvre choisie ont été enregistrés. Nous vous contacterons lorsque la carte sera disponible.",returnArtwork:"Retour à l’œuvre",closeOrder:"Fermer la demande",infoAbout:"Informations sur",loadingHall:"Chargement de la salle",lightingControls:"Réglage de la lumière",chooseArtwork:"Choisir une œuvre",openGuestbook:"Ouvrir le livre d’or",navigation:"Navigation de l’exposition",catalogueFallback:"Votre navigateur ne peut pas afficher les salles en 3D. La vue catalogue est ouverte.",previousWork:"Œuvre précédente",nextWork:"Œuvre suivante",skipContent:"Aller au contenu",morning:"Matin",day:"Journée",evening:"Soir",night:"Nuit" },
  es: { ...en, start:"Comenzar la visita",ready:"La galería está lista",loading:"Preparando la galería",intro:"Entra en una sala tranquila de papel recortado, memoria encontrada y paisajes imaginados.",count:"Una exposición de nueve obras",help:"Ayuda",guestbook:"Libro de visitas",hint:"Arrastra para mirar alrededor. Haz clic en una obra o en la puerta.",order:"Quiero comprar esta postal",back:"Volver a la exposición",close:"Cerrar obra",exhibition:"Exposición en línea",language:"Idioma",returnExhibition:"Volver a la exposición",visitorsYourPage:"Libro de visitas · Tu página",guestbookQuestion:"¿Qué te gustó más?",guestbookIntro:"Deja una breve nota en el libro de visitas. No necesitas cuenta ni correo.",developmentSheets:"Modo desarrollo: conecta Google Sheets para activar los envíos.",displayName:"Nombre",optional:"opcional",yourNote:"Tu mensaje",favouriteArtwork:"Obra favorita",noSelection:"Sin selección",noteSuccess:"Gracias. Tu mensaje se ha añadido al libro de visitas.",leavingNote:"Enviando tu mensaje…",leaveNote:"Dejar este mensaje",noteTooFast:"Tómate un momento antes de enviar tu mensaje.",noteCooldown:"Espera un momento antes de dejar otro mensaje.",noteError:"No se pudo enviar tu mensaje.",noteLength:"Escribe un mensaje un poco más largo.",fromVisitors:"Del libro de visitas",notesHall2:"Mensajes de la Sala 2",demonstration:"Mensajes de demostración",openingGuestbook:"Abriendo el libro…",guestbookError:"No se pudo acceder al libro de visitas.",tryAgain:"Reintentar",emptyGuestbook:"La primera página espera un mensaje.",showMore:"Mostrar más",remembered:"Obra más recordada",anonymous:"Visitante anónimo",postcardRequest:"Solicitud de postal",artwork:"Obra",postcardIntro:"Deja tu correo; te contactaremos cuando la postal esté disponible.",connectSheets:"Conecta Google Sheets para activar los envíos.",sending:"Enviando…",leaveEmail:"Dejar correo",formTooFast:"Tómate un momento antes de enviar.",formCooldown:"Espera un momento antes de volver a enviar.",formError:"No pudimos guardar tu correo. Inténtalo de nuevo.",invalidEmail:"Introduce un correo válido.",received:"Recibido",thankYou:"Gracias.",receivedText:"Tu correo y la obra seleccionada se han guardado. Te contactaremos cuando la postal esté disponible.",returnArtwork:"Volver a la obra",closeOrder:"Cerrar solicitud",infoAbout:"Información sobre",loadingHall:"Cargando la sala",lightingControls:"Controles de iluminación",chooseArtwork:"Elegir una obra",openGuestbook:"Abrir el libro de visitas",navigation:"Navegación de la exposición",catalogueFallback:"Tu navegador no puede mostrar las salas 3D. Se ha abierto la vista de catálogo.",previousWork:"Obra anterior",nextWork:"Obra siguiente",skipContent:"Ir al contenido",morning:"Mañana",day:"Día",evening:"Tarde",night:"Noche" },
  ru: { ...en, start:"Начать выставку",ready:"Галерея готова",loading:"Подготавливаем галерею",intro:"Войдите в тихое пространство бумажных коллажей, найденных воспоминаний и воображаемых пейзажей.",count:"Выставка из девяти работ",help:"Помощь",guestbook:"Книга гостей",hint:"Тяните, чтобы осмотреться вокруг. Нажмите на работу или дверь в следующий зал.",order:"Хочу купить такую открытку",back:"Вернуться на выставку",close:"Закрыть работу",exhibition:"Онлайн-выставка",language:"Язык",returnExhibition:"Вернуться на выставку",visitorsYourPage:"Книга гостей · Ваша страница",guestbookQuestion:"Что вам понравилось больше всего?",guestbookIntro:"Оставьте короткую запись в книге гостей. Аккаунт и email не нужны.",developmentSheets:"Режим разработки: подключите Google Sheets для отправки.",displayName:"Имя",optional:"необязательно",yourNote:"Ваш отзыв",favouriteArtwork:"Любимая работа",noSelection:"Не выбрано",noteSuccess:"Спасибо. Ваш отзыв добавлен в книгу гостей.",leavingNote:"Отправляем отзыв…",leaveNote:"Оставить отзыв",noteTooFast:"Не торопитесь — допишите отзыв перед отправкой.",noteCooldown:"Подождите немного перед следующим отзывом.",noteError:"Не удалось отправить отзыв.",noteLength:"Пожалуйста, напишите отзыв немного подробнее.",fromVisitors:"Из книги гостей",notesHall2:"Отзывы из Зала 2",demonstration:"Демонстрационные записи",openingGuestbook:"Открываем книгу гостей…",guestbookError:"Не удалось открыть книгу гостей.",tryAgain:"Повторить",emptyGuestbook:"Первая страница ждёт отзыва.",showMore:"Показать ещё",remembered:"Больше всего запомнилась",anonymous:"Анонимный посетитель",postcardRequest:"Заказ открытки",artwork:"Работа",postcardIntro:"Оставьте email — мы свяжемся с вами, когда открытка будет доступна.",connectSheets:"Подключите Google Sheets, чтобы включить отправку формы.",sending:"Отправляем…",leaveEmail:"Оставить email",formTooFast:"Подождите немного перед отправкой.",formCooldown:"Подождите перед повторной отправкой.",formError:"Не удалось сохранить email. Попробуйте ещё раз.",invalidEmail:"Введите корректный email.",received:"Получено",thankYou:"Спасибо.",receivedText:"Ваш email и выбранная работа сохранены. Мы свяжемся с вами, когда открытка будет доступна.",returnArtwork:"Вернуться к работе",closeOrder:"Закрыть форму заказа",infoAbout:"Информация о работе",loadingHall:"Загружаем зал",lightingControls:"Управление освещением",chooseArtwork:"Выбрать работу",openGuestbook:"Открыть книгу гостей",navigation:"Навигация по выставке",catalogueFallback:"Браузер не может показать 3D-залы. Открыта версия в виде каталога.",previousWork:"Предыдущая работа",nextWork:"Следующая работа",skipContent:"Перейти к содержанию",morning:"Утро",day:"День",evening:"Вечер",night:"Ночь" },
  it: { ...en, start:"Inizia la visita",ready:"La galleria è pronta",loading:"Preparazione della galleria",intro:"Entra in una sala silenziosa di carta ritagliata, memorie ritrovate e paesaggi immaginati.",count:"Una mostra di nove opere",help:"Aiuto",guestbook:"Libro degli ospiti",hint:"Trascina per guardarti intorno. Fai clic su un’opera o sulla porta.",order:"Voglio comprare questa cartolina",back:"Torna alla mostra",close:"Chiudi opera",exhibition:"Mostra online",language:"Lingua",returnExhibition:"Torna alla mostra",visitorsYourPage:"Libro degli ospiti · La tua pagina",guestbookQuestion:"Cosa ti è piaciuto di più?",guestbookIntro:"Lascia un breve messaggio nel libro degli ospiti. Non servono account o email.",developmentSheets:"Modalità sviluppo: collega Google Sheets per abilitare gli invii.",displayName:"Nome",optional:"facoltativo",yourNote:"Il tuo messaggio",favouriteArtwork:"Opera preferita",noSelection:"Nessuna selezione",noteSuccess:"Grazie. Il tuo messaggio è stato aggiunto al libro degli ospiti.",leavingNote:"Invio del messaggio…",leaveNote:"Lascia il messaggio",noteTooFast:"Prenditi un momento prima di inviare.",noteCooldown:"Attendi prima di lasciare un altro messaggio.",noteError:"Non è stato possibile inviare il messaggio.",noteLength:"Scrivi un messaggio un po’ più lungo.",fromVisitors:"Dal libro degli ospiti",notesHall2:"Messaggi dalla Sala 2",demonstration:"Messaggi dimostrativi",openingGuestbook:"Apertura del libro…",guestbookError:"Il libro degli ospiti non è raggiungibile.",tryAgain:"Riprova",emptyGuestbook:"La prima pagina attende un messaggio.",showMore:"Mostra altro",remembered:"Opera più ricordata",anonymous:"Visitatore anonimo",postcardRequest:"Richiesta cartolina",artwork:"Opera",postcardIntro:"Lascia la tua email: ti contatteremo quando la cartolina sarà disponibile.",connectSheets:"Collega Google Sheets per abilitare gli invii.",sending:"Invio…",leaveEmail:"Lascia l’email",formTooFast:"Attendi un momento prima di inviare.",formCooldown:"Attendi prima di inviare di nuovo.",formError:"Non è stato possibile salvare l’email. Riprova.",invalidEmail:"Inserisci un indirizzo email valido.",received:"Ricevuto",thankYou:"Grazie.",receivedText:"La tua email e l’opera scelta sono state salvate. Ti contatteremo quando la cartolina sarà disponibile.",returnArtwork:"Torna all’opera",closeOrder:"Chiudi la richiesta",infoAbout:"Informazioni su",loadingHall:"Caricamento della sala",lightingControls:"Controlli luce",chooseArtwork:"Scegli un’opera",openGuestbook:"Apri il libro degli ospiti",navigation:"Navigazione della mostra",catalogueFallback:"Il browser non può mostrare le sale 3D. È aperta la vista catalogo.",previousWork:"Opera precedente",nextWork:"Opera successiva",skipContent:"Vai al contenuto",morning:"Mattina",day:"Giorno",evening:"Sera",night:"Notte" },
  sr: { ...en, start:"Započni obilazak",ready:"Galerija je spremna",loading:"Pripremamo galeriju",intro:"Uđite u tihu sobu isečenog papira, pronađenih sećanja i zamišljenih pejzaža.",count:"Izložba od devet radova",help:"Pomoć",guestbook:"Knjiga utisaka",hint:"Prevucite da biste pogledali oko sebe. Kliknite na rad ili vrata.",order:"Želim da kupim ovu razglednicu",back:"Nazad na izložbu",close:"Zatvori rad",exhibition:"Onlajn izložba",language:"Jezik",returnExhibition:"Nazad na izložbu",visitorsYourPage:"Knjiga utisaka · Vaša stranica",guestbookQuestion:"Šta vam se najviše dopalo?",guestbookIntro:"Ostavite kratku poruku u knjizi utisaka. Nalog i email nisu potrebni.",developmentSheets:"Razvojni režim: povežite Google Sheets da omogućite slanje.",displayName:"Ime",optional:"opciono",yourNote:"Vaša poruka",favouriteArtwork:"Omiljeni rad",noSelection:"Bez izbora",noteSuccess:"Hvala. Vaša poruka je dodata u knjigu utisaka.",leavingNote:"Slanje poruke…",leaveNote:"Ostavi poruku",noteTooFast:"Sačekajte trenutak pre slanja poruke.",noteCooldown:"Sačekajte pre nego što ostavite novu poruku.",noteError:"Poruka nije mogla biti poslata.",noteLength:"Napišite malo dužu poruku.",fromVisitors:"Iz knjige utisaka",notesHall2:"Poruke iz Sale 2",demonstration:"Probni unosi",openingGuestbook:"Otvaranje knjige…",guestbookError:"Knjiga utisaka nije dostupna.",tryAgain:"Pokušaj ponovo",emptyGuestbook:"Prva stranica čeka poruku.",showMore:"Prikaži još",remembered:"Najviše se pamti",anonymous:"Anonimni posetilac",postcardRequest:"Zahtev za razglednicu",artwork:"Rad",postcardIntro:"Ostavite email — javićemo vam se kada razglednica bude dostupna.",connectSheets:"Povežite Google Sheets da omogućite slanje.",sending:"Slanje…",leaveEmail:"Ostavi email",formTooFast:"Sačekajte trenutak pre slanja.",formCooldown:"Sačekajte pre ponovnog slanja.",formError:"Email nije sačuvan. Pokušajte ponovo.",invalidEmail:"Unesite važeću email adresu.",received:"Primljeno",thankYou:"Hvala.",receivedText:"Vaš email i izabrani rad su sačuvani. Javićemo vam se kada razglednica bude dostupna.",returnArtwork:"Nazad na rad",closeOrder:"Zatvori zahtev",infoAbout:"Informacije o",loadingHall:"Učitavanje sale",lightingControls:"Kontrole osvetljenja",chooseArtwork:"Izaberite rad",openGuestbook:"Otvori knjigu utisaka",navigation:"Navigacija izložbe",catalogueFallback:"Pregledač ne može da prikaže 3D sale. Otvoren je prikaz kataloga.",previousWork:"Prethodni rad",nextWork:"Sledeći rad",skipContent:"Pređi na sadržaj",morning:"Jutro",day:"Dan",evening:"Veče",night:"Noć" }
};

interface LanguageContextValue { language: Language; setLanguage: (language: Language) => void; t: (key: MessageKey) => string; }
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  useEffect(() => {
    const saved = window.localStorage.getItem("exhibition-language");
    const browser = navigator.language.slice(0, 2);
    const initial = languages.includes(saved as Language) ? (saved ?? "en") : browser;
    if (languages.includes(initial as Language)) setLanguageState(initial as Language);
    document.documentElement.lang = languages.includes(initial as Language) ? initial : "en";
  }, []);
  const setLanguage = (next: Language) => { setLanguageState(next); window.localStorage.setItem("exhibition-language", next); document.documentElement.lang = next; };
  const value = useMemo(() => ({ language, setLanguage, t: (key: MessageKey) => messages[language][key] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error("LanguageProvider is missing"); return value; }
export function LanguageSelector({ className = "" }: { className?: string }) {
  const { language, setLanguage, t } = useLanguage();
  return <label className={`inline-flex ${className}`}><span className="sr-only">{t("language")}</span><select aria-label={t("language")} value={language} onChange={(event) => setLanguage(event.target.value as Language)} className="cursor-pointer bg-transparent text-[10px] uppercase tracking-[.16em]">{languages.map((code) => <option key={code} value={code}>{labels[code]}</option>)}</select></label>;
}
export type { MessageKey };
